title: Gan Eng Seng School
url: https://ganengsengsch.moe.edu.sg
favicon: /images/gess_logo1.png
colors:
  primary-color: "#262626"
  secondary-color: "#e7b141"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#498405"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: Gan Eng Seng School (GESS) is a co-educational government secondary
  school in Bukit Merah, Singapore. Founded in 1885 by philanthropist Gan Eng
  Seng, the school is the first school established by the overseas Chinese
  community in Singapore and is one of the oldest schools in the country.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d27edpgfp63vob.amplifyapp.com
prod: https://master.d27edpgfp63vob.amplifyapp.com
resources_name: resources
shareicon: /images/GESS_Crest_Transparent_V2.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
google_analytics_ga4: ""
